In [1]:


import numpy as np


In [4]:
# 1.Write a NumPy program to create an array of 10 zeros
a= np.zeros(10, dtype=int)
print(a)

[0 0 0 0 0 0 0 0 0 0]


In [8]:
# 2.Write a NumPy program to create an array of 10 ones.
a= np.ones(10, dtype=int)
print(a)

[1 1 1 1 1 1 1 1 1 1]


In [10]:
#3. Write a NumPy program to create a 3x3 matrix with values ranging from 0 to 8.

np.random.randint(1,8,(3,3))


array([[7, 7, 6],
       [6, 2, 2],
       [5, 2, 6]], dtype=int32)

In [19]:
# 4.Write a NumPy program to reverse an array (first element becomes the last).
x=[1,2,3,4]
rx=np.array(x)
print(rx[::-1])

[4 3 2 1]


In [ ]:
# 5.Write a NumPy program to extract all odd numbers from an array.
import numpy as np
a=[12,23,32,1,7,98]
nx= np.array(a)
print(nx[nx%2!=0])

[23  1  7]
