In [2]:
import numpy as np

In [3]:
x= [[1,2],[3,4]]
total=0
for i in x:
    total+=sum(i)
print(total)

10


In [4]:
# with help of numpy
x= [[1,2],[3,4]]
nx= np.array(x)


In [5]:
print(nx.sum())
print(nx.min())
print(nx.var())
print(nx.mean())

10
1
1.25
2.5


In [6]:
print(nx.shape)
print(nx.dtype)

(2, 2)
int64


functions to create matrix
- arrange
- linspace
- ones
- zeros
- random.randit
- random.rand
- diag

In [7]:
y= [[2,4,5],[6,12,2],[2,9,6]]
px= np.array(y)

In [8]:
a= np.arange(1,50)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [9]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [10]:
np.linspace(1,2,10)


array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [11]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones((2,2))


array([[1., 1.],
       [1., 1.]])

In [14]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
np.zeros((2,6), dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [16]:
np.random.randint(1,100,10)

array([49, 12, 47, 66, 52, 10, 48, 80, 42, 51], dtype=int32)

In [17]:
np.random.randint(-5,5,(3,3))

array([[-4, -4, -1],
       [-3, -3, -2],
       [ 3, -3, -2]], dtype=int32)

In [18]:
np.random.rand(5,5)

array([[0.16189308, 0.99563127, 0.65120568, 0.64383005, 0.79028549],
       [0.8928917 , 0.72834548, 0.90051871, 0.18023517, 0.46544421],
       [0.82869831, 0.86361361, 0.58563115, 0.41737694, 0.36748757],
       [0.93790273, 0.04824804, 0.93074292, 0.89320628, 0.97643975],
       [0.92663367, 0.24704571, 0.67337151, 0.66759812, 0.35958012]])

In [19]:
np.set_printoptions(precision=2)
np.random.rand(5,5)

array([[0.24, 0.48, 0.87, 0.51, 0.9 ],
       [0.68, 0.85, 0.97, 0.11, 0.38],
       [0.6 , 0.26, 0.25, 0.11, 0.84],
       [0.56, 0.04, 0.83, 0.98, 0.66],
       [0.01, 0.87, 0.84, 0.27, 0.44]])

In [20]:
x=[1,2,3,4,5]
np.diag(x)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [21]:
# reshape

np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
x=np.linspace(1,10,25,dtype=int).reshape(5,5)
print(x)

[[ 1  1  1  2  2]
 [ 2  3  3  4  4]
 [ 4  5  5  5  6]
 [ 6  7  7  7  8]
 [ 8  8  9  9 10]]


In [23]:
x.T # transpose


array([[ 1,  2,  4,  6,  8],
       [ 1,  3,  5,  7,  8],
       [ 1,  3,  5,  7,  9],
       [ 2,  4,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [24]:
a= np.random.randint(1,10,(3,3))
b= np.random.randint(1,10,(3,3))

In [25]:
a+b

array([[ 8,  6,  5],
       [11,  7, 11],
       [ 3,  2, 14]], dtype=int32)

In [26]:
a*b

array([[12,  8,  6],
       [30, 12, 24],
       [ 2,  1, 48]], dtype=int32)

In [27]:
a-b

array([[ 4, -2, -1],
       [ 1, -1,  5],
       [ 1,  0, -2]], dtype=int32)

In [28]:
a.dot(b)# matrix multiplication

array([[24, 34, 40],
       [35, 44, 91],
       [15, 18, 57]], dtype=int32)

Stats

In [29]:
print(a.mean())

4.0


In [30]:
print(a.mean(axis=0)) # column wise mean
print(a.mean(axis=1)) # rows wise

[4.67 2.   5.33]
[3.33 5.67 3.  ]


In [31]:
print(a.std())
print(a.std(axis=1))

2.3570226039551585
[1.89 2.05 2.16]


In [32]:
print(a.max())
print(a.shape)

8
(3, 3)


In [33]:
print(np.exp(a))
print(np.max(a))

[[4.03e+02 7.39e+00 7.39e+00]
 [4.03e+02 2.01e+01 2.98e+03]
 [7.39e+00 2.72e+00 4.03e+02]]
8


In [34]:
p= np.random.randint(1,100,(2,5))
print(x)

[[ 1  1  1  2  2]
 [ 2  3  3  4  4]
 [ 4  5  5  5  6]
 [ 6  7  7  7  8]
 [ 8  8  9  9 10]]


In [35]:
print(p.max())
print(p.argmax())
print(p.min())

97
7
3


- slicing
  - 1D [start stop step]

In [38]:
x= np.arange(1,11)
print(x[:5])
print(x[-5:])

[1 2 3 4 5]
[ 6  7  8  9 10]


In [44]:
x= np.linspace(1,100,25).reshape(5,5).astype(int)
print(x)

print(x[0])# row index 0
print(x[-1]) # last row
print(x[2])# row index2
print(x[:3])


[[  1   5   9  13  17]
 [ 21  25  29  34  38]
 [ 42  46  50  54  58]
 [ 62  67  71  75  79]
 [ 83  87  91  95 100]]
[ 1  5  9 13 17]
[ 83  87  91  95 100]
[42 46 50 54 58]
[[ 1  5  9 13 17]
 [21 25 29 34 38]
 [42 46 50 54 58]]


In [49]:
print(x[:,0])
print(x[:,-1])


[ 1 21 42 62 83]
[ 17  38  58  79 100]
[ 9 29 50 71 91]


In [50]:
print(x[:,-3])

[ 9 29 50 71 91]


In [54]:
print(x[1:-1:3])

[[21 25 29 34 38]]


In [55]:
print(x[2:-1,2:])

[[50 54 58]
 [71 75 79]]


filtering

In [56]:
x

array([[  1,   5,   9,  13,  17],
       [ 21,  25,  29,  34,  38],
       [ 42,  46,  50,  54,  58],
       [ 62,  67,  71,  75,  79],
       [ 83,  87,  91,  95, 100]])

In [57]:
x>50 # boolean array

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [58]:
x[x>50] # broadcasting

array([ 54,  58,  62,  67,  71,  75,  79,  83,  87,  91,  95, 100])

In [59]:
x[(x>40)&(x<80)]

array([42, 46, 50, 54, 58, 62, 67, 71, 75, 79])

In [63]:
x[x%2==0]


array([ 34,  38,  42,  46,  50,  54,  58,  62, 100])

In [62]:
x[x%2 !=0]

array([ 1,  5,  9, 13, 17, 21, 25, 29, 67, 71, 75, 79, 83, 87, 91, 95])