In [1]:
import numpy as np

In [6]:
x= [[1,2],[3,4]]
total=0
for i in x:
    total+=sum(i)
print(total)

10


In [9]:
# with help of numpy
x= [[1,2],[3,4]]
nx= np.array(x)


In [20]:
print(nx.sum())
print(nx.min())
print(nx.var())
print(nx.mean())

10
1
1.25
2.5


In [19]:
print(nx.shape)
print(nx.dtype)

(2, 2)
int64


functions to create matrix
- arrange
- linspace
- ones
- zeros
- random.randit
- random.rand
- diag

In [21]:
y= [[2,4,5],[6,12,2],[2,9,6]]
px= np.array(y)

In [22]:
a= np.arange(1,50)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [26]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [31]:
np.linspace(1,2,10)


array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [30]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [32]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
np.ones((2,2))


array([[1., 1.],
       [1., 1.]])

In [34]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [38]:
np.zeros((2,6), dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [39]:
np.random.randint(1,100,10)

array([37, 23, 72, 45, 70, 25, 86, 98, 90, 50], dtype=int32)

In [43]:
np.random.randint(-5,5,(3,3))

array([[-5,  2, -2],
       [-4, -4,  1],
       [-5, -5,  1]], dtype=int32)

In [45]:
np.random.rand(5,5)

array([[0.28792575, 0.92135009, 0.09626615, 0.7821832 , 0.75657039],
       [0.92528106, 0.74987766, 0.48613445, 0.77290449, 0.6691367 ],
       [0.42309975, 0.2089058 , 0.93210994, 0.12015881, 0.18708627],
       [0.70247816, 0.17506831, 0.65138699, 0.9070124 , 0.06338621],
       [0.17397218, 0.35594395, 0.25355371, 0.86922972, 0.73864001]])

In [49]:
np.set_printoptions(precision=2)
np.random.rand(5,5)

array([[0.21, 0.45, 0.74, 0.41, 0.84],
       [0.12, 0.95, 0.47, 0.39, 0.85],
       [0.33, 0.92, 0.4 , 0.54, 0.88],
       [0.07, 0.55, 0.8 , 0.57, 0.07],
       [0.42, 0.1 , 0.69, 0.92, 0.37]])

In [50]:
x=[1,2,3,4,5]
np.diag(x)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [55]:
# reshape

np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [61]:
x=np.linspace(1,10,25,dtype=int).reshape(5,5)
print(x)

[[ 1  1  1  2  2]
 [ 2  3  3  4  4]
 [ 4  5  5  5  6]
 [ 6  7  7  7  8]
 [ 8  8  9  9 10]]


In [62]:
x.T # transpose


array([[ 1,  2,  4,  6,  8],
       [ 1,  3,  5,  7,  8],
       [ 1,  3,  5,  7,  9],
       [ 2,  4,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [63]:
a= np.random.randint(1,10,(3,3))
b= np.random.randint(1,10,(3,3))

In [64]:
a+b

array([[ 9,  6, 14],
       [13, 12, 12],
       [10, 17,  7]], dtype=int32)

In [65]:
a*b

array([[ 8,  8, 48],
       [36, 27, 27],
       [16, 72,  6]], dtype=int32)

In [66]:
a-b

array([[ 7,  2,  2],
       [-5, -6, -6],
       [ 6,  1, -5]], dtype=int32)

In [67]:
a.dot(b)# matrix multiplication

array([[ 60, 116, 132],
       [ 37,  59,  69],
       [ 91, 105, 135]], dtype=int32)

Stats

In [68]:
print(a.mean())

5.333333333333333


In [70]:
print(a.mean(axis=0)) # column wise mean
print(a.mean(axis=1)) # rows wise

[6.67 5.33 4.  ]
[6.67 3.33 6.  ]


In [72]:
print(a.std())
print(a.std(axis=1))

2.748737083745107
[1.89 0.47 3.56]


In [75]:
print(a.max())
print(a.shape)

9
(3, 3)


In [77]:
print(np.exp(a))
print(np.max(a))

[[2.98e+03 5.46e+01 2.98e+03]
 [5.46e+01 2.01e+01 2.01e+01]
 [2.98e+03 8.10e+03 2.72e+00]]
9


In [79]:
p= np.random.randint(1,100,(2,5))
print(x)

[[ 1  1  1  2  2]
 [ 2  3  3  4  4]
 [ 4  5  5  5  6]
 [ 6  7  7  7  8]
 [ 8  8  9  9 10]]


In [84]:
print(p.max())
print(p.argmax())
print(p.min())

87
1
3
